version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
  frontend:
    build: ./src/main/frontend
    ports:
      - "8082:80"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pokimages
      POSTGRES_USER: ia
      POSTGRES_PASSWORD: foufafou
    ports:
      - "5432:5432"