# pokimages/docker-compose.yml
version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Port hôte 8081 -> Port conteneur 8081
    depends_on:
      - db
  frontend:
    build:
      context: ./src/main/frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"  # Port hôte 8082 -> Port conteneur 80 (Nginx)
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pokimages
      POSTGRES_USER: ia
      POSTGRES_PASSWORD: foufafou
    ports:
      - "5432:5432"